name = "Parallelism"
uuid = "c8c83da1-e5f9-4e2c-a857-b8617bac3554"
authors = ["Invenia Technical Computing Corporation"]
version = "0.1.0"

[deps]
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Memento = "f28f55f0-a522-5efc-85c2-fe41dfb9b2d9"

[compat]
Memento = "0.11, 0.12, 0.13, 1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
